/**
 * Generate .env.test for CI environment.
 *
 * This script creates the .env.test file with CI-safe placeholder values.
 * Used by base-ci workflow's pre-command to set up the test environment
 * before running L2/L3 tests.
 *
 * The values here are placeholders — actual email sending is disabled via
 * EMAIL_DRY_RUN=true, and D1 uses local SQLite (no remote connection).
 */

import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_PATH = resolve(ROOT, ".env.test");

const CI_ENV_CONTENT = `# Generated by scripts/setup-ci-env.ts for CI
D1_WORKER_URL=http://localhost:17034
D1_WORKER_API_KEY=ci-placeholder
EMAIL_DRY_RUN=true
RESEND_DRY_RUN=true
DEV_MODE=true
RESEND_API_KEY=re_ci_placeholder_not_real
RESEND_FROM_DOMAIN=test.example.com
`;

if (existsSync(ENV_PATH)) {
  console.log(".env.test already exists, skipping generation");
} else {
  writeFileSync(ENV_PATH, CI_ENV_CONTENT);
  console.log(".env.test generated for CI");
}
